apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gynecare.fullname" . }}-config
  labels:
    {{- include "gynecare.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}
  PORT: {{ .Values.backend.env.port | quote }}
  MONGO_URI: "mongodb://{{ include "gynecare.fullname" . }}-mongo:{{ .Values.mongodb.service.port }}/{{ .Values.mongodb.database }}"
