apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gynecare.fullname" . }}-mongo
  labels:
    app.kubernetes.io/component: database
    {{- include "gynecare.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gynecare.name" . }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gynecare.name" . }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
              name: mongodb
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          {{- if .Values.mongodb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "gynecare.fullname" . }}-mongo-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
