apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gynecare.fullname" . }}-secret
  labels:
    {{- include "gynecare.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.backend.env.geminiApiKey | default "" | quote }}
