apiVersion: v1
kind: Service
metadata:
  name: {{ include "gynecare.fullname" . }}-mongo
  labels:
    app.kubernetes.io/component: database
    {{- include "gynecare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: {{ include "gynecare.name" . }}
    app.kubernetes.io/component: database
