# ==============================================================================
# Ansible Inventory for Nginx Multi-Server Case Study (Assignment 8)
# ==============================================================================

[webservers]
nginx-01 ansible_host=172.28.0.11 ansible_user=ansible ansible_port=22
nginx-02 ansible_host=172.28.0.12 ansible_user=ansible ansible_port=22
nginx-03 ansible_host=172.28.0.13 ansible_user=ansible ansible_port=22

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
web_server_title="GyneCare Healthcare Portal - Managed via Ansible"
