apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gynecare-mongo-pvc
  namespace: gynecare-dev
  labels:
    app: gynecare-mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
