apiVersion: v1
kind: PersistentVolume
metadata:
  name: gynecare-mongo-pv
  labels:
    type: local
    app: gynecare-mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/gynecare-mongo"
